name: LAMP CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Lint PHP Code
        run: vendor/bin/phpcs --standard=PSR12 src/

